import Rodape from "./componentes/Rodape";
import "./globals.css";
import Topo from "@/app/componentes/Topo";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
};
export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <Topo/>
        {children}
        <Rodape/>
      </body>
    </html>
  );
}
